### ISSUE TITLE
Convert LatLon to UTM

### ISSUE THREAD

**Issue by Jonybang** [galtspace/galtproject-contracts#346]
https://github.com/chrisveness/geodesy/blob/master/utm.js
http://math2.org/math/algebra/functions/sincos/properties.htm
- [x] Move main logic from Javascript to Solidity (120)
- [x] Get latBand based on index (60)
- [x] Move sinh and asinh methods to Solidity (120)
- [x] Move tan, atan, cos to Solidity (120)
- [x] Solve problems with no-float paradigm on Solidity for current algorithm (120)
- [x] Make and use bytes32 data structure for UTM (120)
- [x] Caching UTM data in SplitMerge by geohashes for re-use later (60)
- [x] Write tests (60)

**Comment by Jonybang** [comment]
https://ethereum.stackexchange.com/questions/8086/logarithm-math-operation-in-solidity

**Comment by Jonybang** [comment]
http://math2.org/math/algebra/functions/sincos/properties.htm
